package br.thelma.armidoro.api.domain.paciente;

public enum GrauEscolaridade {
    SEM_ESCOLARIDADE,
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_FUNDAMENTAL_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    ENSINO_SUPERIOR_INCOMPLETO,
    ENSINO_SUPERIOR_COMPLETO,
    POS_GRADUACAO,
    MESTRADO,
    DOUTORADO,
    OUTROS
}
